### ISSUE TITLE
Forestry 3.6 support?

### ISSUE THREAD

**Issue by canilsen** [Tonius/NEI-Integration#101] opened 2015-12-20 09:40 UTC
Forestry support was removed because 4.0 got its own nei integration. But a lot still uses 3.6 because of binnie mods.

Could the devs please add 3.6 support back in? Even set to false as default in config would be great, so us with 3.6 can enable it.

**Comment by Tonius** [comment] 2015-12-21 22:04
Duplicate of #100 (sort of)

**Closed by Tonius** 2015-12-21 22:04 UTC
